general:
  debug: false
  instance_name: "TokBina SearXNG"
  contact_url: "mailto:hello@tokbina.com"

search:
  safe_search: 0
  autocomplete: "google"

server:
  port: 8080
  bind_address: "0.0.0.0"

engines:
  - name: google
    engine: google_noapi
    shortcut: g
    network: all

  - name: bing
    engine: bing
    shortcut: bi
    network: all

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    network: all

  - name: reddit
    engine: reddit
    shortcut: rd
    network: all

  - name: stackoverflow
    engine: stackexchange
    shortcut: so
    api_site: 'stackoverflow'
    network: all

  - name: github
    engine: github
    shortcut: gh
    network: all

outgoing:
  proxies:
    all:
      - http://qcecuaqv:06batax2lozw@proxy.webshare.io:80

ui:
  static_use_hash: true
  theme: oscar
  infinite_scroll: true
